anna-popova/Transformation

index.html

Добавлен footer с Яндекс метрикой

#14 Footer created

---

index.html

https://github.com/Flavissimo/Transformation/issues/42

issue #42 input mask phone

---

index.html

add attribute data-interval in slider HTML-tag

#108 disabled autorun sliding "photo-results"

---

index.html

удалил параграф сроки преобраражения 6.0

#110 Removed paragraph in price

---

index.html

#116 update price

---

index.html

#135 update prices

---

index.html

#139 update news

---

index.html

#143 fixed mistake in block news

---

css/style.css
index.html

#145 set the text to center

---

css/style.css
index.html

This reverts commit 076ea121db8a030dcf7b27f198e907ed6d2fa821.

Revert "#145 set the text to center"

---

css/style.css
index.html

#152 update block "results"

---

css/style.css
index.html

#146 delete fluid

---

css/style.css
index.html

#161 deleted id in css

---

css/style.css
index.html

#154 update block 'FAQ'

---

.gitignore
css/style.css
index.html

Перед стартом нового потока убрал самое некрасивое

Пару быстрых изменений

---

index.html

Дорогая Александра, буду благодарен, если нажмете кнопочку "Принять"

Минорные, но срочные изменения

---

.editorconfig

#162
- Update css indent styles for .editorconfig project file

#162 update css indent styles for editorconfig

---

css/style.css
index.html

Removing bootstrap classes, rewriting to BEM

---

index.html

Fix #176 change price

---

.editorconfig
css/style.css
index.html

наименования [*.yml], [lib/**.js], [*.css] оставила на случай, если необходимо будет там прописать конфигурации.
если будет нужно - уберу.

fix #185 improve editorconfig

---

css/style.css
index.html

changing index.html, adding relevant info
